# Generated by Django 3.1.14 on 2021-12-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_pokemonentity_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='apperated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disapperated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
