# Generated by Django 3.1.14 on 2021-12-26 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20211226_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Покемон', 'verbose_name_plural': 'Покемоны'},
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='tree_id',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evolution', to='pokemon_entities.pokemon', verbose_name='Родитель'),
        ),
    ]
